### ISSUE TITLE
Impacts fx and sound table values for weapon gdt files are not exported

### ISSUE THREAD

**Issue by Sandwichas** [Scobalula/HydraX#3]
![Screenshot_12](https://github.com/user-attachments/assets/13863fb7-d20c-40ac-8273-ea0de0087ddf)
As seen from the image above, no values can be seen in the textboxes. A weapon of bullet_small impact type should normally have these values:
![Screenshot_13](https://github.com/user-attachments/assets/988aa4e7-5d04-4c89-8a6f-5718c70ad40c)
Thanks.

**Comment by Scobalula** [comment]
Fixed in https://github.com/Scobalula/HydraX/releases/tag/3.8.0.0
